SELECT
    PES.NU_IE,
    PES.NU_CNPJ,
    PES.NU_IE_ST,
    PES.CD_MUN_ANALIT,
    MUN.NM_MUN_IBGE,
    PES.CD_UF,
    UF.CD_SIGLA_UF,
    PES.CD_PESSOA_ARE,
    ARE.CD_PESSOA_ARE_CENTR,
    ARC.CD_PESSOA_DRR,
    DRR.CD_DRR,
    DRR.DS_DRR,
    SUM(GIA.VL_ICMS_DIFAL) AS Difal
FROM    P_ACCDB.FAT_GIA GIA
INNER JOIN P_ACCDB.DIM_PESSOA PES
ON (GIA.CD_PESSOA = PES.CD_PESSOA)
INNER JOIN P_ACCDB.DIM_END ENDE
ON (PES.CD_PESSOA = ENDE.CD_PESSOA)
INNER JOIN P_ACCDB.DIM_MUNICIPIO MUN
ON (PES.CD_MUN_ANALIT = MUN.CD_MUN_ANALIT)
INNER JOIN P_ACCDB.DIM_ARE ARE
ON (PES.CD_PESSOA_ARE = ARE.CD_PESSOA)
INNER JOIN P_ACCDB.DIM_ARE_CENTRALIZADORA ARC
ON (PES.CD_PESSOA_ARE_CENTR = ARC.CD_PESSOA)
INNER JOIN P_ACCDB.DIM_DRR DRR
ON (PES.CD_PESSOA_DRR = DRR.CD_PESSOA)
INNER JOIN P_ACCDB.DIM_UF UF
ON (PES.CD_UF = UF.CD_UF)
WHERE
    GIA.CD_TIPO_DOC_GIA = 2
    AND GIA.DT_ANO_MES_REF BETWEEN '202204' AND '202512'
GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12
ORDER BY 13 DESC
