SELECT 
    DF.NM_EMIT AS NmEmit,
    DF.CD_CNPJ_CPF_EMIT AS CNPJEmit,
    ENDE.CD_SIGLA_UF AS UFEmit,
    COUNT(DISTINCT DF.CD_CHAVE_DFE) AS QTD_DOC,
    SUM(ITEM.VL_TOTAL) AS TOTAL_ITEM,
    SUM(ITEM.VL_ICMS_UF_DEST) AS DIFAL_DEST

FROM P_ACCDB.FAT_DOC_FISC DF

INNER JOIN P_ACCDB.FAT_ITEM ITEM
    ON DF.CD_DOC_FISC = ITEM.CD_DOC_FISC
   AND DF.DT_EMIS_DOC_FISC = ITEM.DT_EMIS_DOC_FISC
   AND DF.CD_SIST_ORIG = ITEM.CD_SIST_ORIG

LEFT JOIN P_ACCDB.DIM_PARTICP_DOC_FISC ENDE
    ON DF.CD_PARTICP_EMIT = ENDE.CD_PARTICP_DOC_FISC

LEFT JOIN P_ACCDB.DIM_PARTICP_DOC_FISC ENDD
    ON DF.CD_PARTICP_DEST = ENDD.CD_PARTICP_DOC_FISC

LEFT JOIN P_ACCDB.DIM_PARTICP_DOC_FISC ENDR
    ON DF.CD_PARTICP_REMET = ENDR.CD_PARTICP_DOC_FISC

LEFT JOIN P_ACCDB.DIM_TIPO_SIT_TRIB CST
    ON ITEM.CD_SIT_TRIB_ICMS = CST.CD_SIT_TRIB

WHERE
    DF.CD_SIT_DOC_FISC = 1 -- AUTORIZADOS
    AND DF.CD_SIST_ORIG = 1 -- NFE
    AND DF.CD_UF_EMIT <> 41
    AND ITEM.CD_CFOP > 6000
    AND DF.CD_TIPO_IE_DEST = 9
    AND ITEM.VL_ICMS_UF_DEST > 0
    AND DF.DT_EMIS_DOC_FISC BETWEEN DATE '2022-04-05' AND DATE '2025-12-31'

   
GROUP BY 
    1, 2, 3

ORDER BY 
    6 DESC;
